### ISSUE TITLE
Waiting for H298A V9 support

### ISSUE THREAD

**Issue by sivasspor** [mkst/zte-config-utility#38] opened 2022-03-10 22:34 UTC
**Description of new feature**
 I would like the H298A V9 router to be supported

**Describe alternatives you've considered**
C:\Users\Yusuf\Desktop\zte-config-utility-master>py examples/decode.py --serial ZTC094AD61Axxx config.bin config.xml
Signature: H298A V9
Failed! Trying again, with signature: H298AV9
Malformed decrypted payload, likely you used the wrong key!

**Comment by aycanuAydemir** [comment] 2022-08-08 17:12
+1

**Comment by Aokromes** [comment] 2022-11-05 23:40
duplicate of https://github.com/mkst/zte-config-utility/issues/31

**Comment by akahmet** [comment] 2022-12-13 12:47
Not an unpacker but you can root your router with this script.

https://github.com/gibirnet/H298A-V9-Rooter

**Comment by mkst** [comment] 2023-02-16 17:19
closing as dupe of https://github.com/mkst/zte-config-utility/issues/31

**Closed by mkst** 2023-02-16 17:19 UTC
