### ISSUE TITLE
 H298A V9 is not supported

### ISSUE THREAD

**Issue by Okksx** [mkst/zte-config-utility#46] opened 2022-07-08 16:54 UTC
**Description of new feature**
I would like the H298A V9 router to be supported

**Describe alternatives you've considered**
I have tried using py examples/decode.py --serial ZTA87XXX--signature 'H298AV9' config.bin config.xml but I get the following error < Signature: H298A V9
Failed! Trying again, with signature: H298AV9
Malformed decrypted payload, likely you used the wrong key! >

**Attach config.bin for your device**
I can add later if needed

**Comment by eoksum** [comment] 2022-08-06 16:27
I can verify this tool isn't working on H298A V9. Just tried it today.

**Comment by eserozvataf** [comment] 2022-08-08 09:08
same here :(

**Comment by aycanuAydemir** [comment] 2022-08-08 17:12
+1

**Comment by Vfynex** [comment] 2022-10-20 20:08
+1 still update

**Comment by Gorkido** [comment] 2022-11-01 14:47
![image](https://user-images.githubusercontent.com/81165187/199261411-934345af-1393-4266-b892-eef5ababd263.png)

i also tried `--try-all-known-keys`.
it returned error: **"Failed to decrypt type 4 payload, tried 4 generated key(s)!"**

**Comment by Aokromes** [comment] 2022-11-05 23:40
duplicate of https://github.com/mkst/zte-config-utility/issues/31

**Comment by krttokaan** [comment] 2022-12-05 15:41
++++

**Comment by mkst** [comment] 2023-02-16 17:21
Dlosing as dupe of https://github.com/mkst/zte-config-utility/issues/31.

**Closed by mkst** 2023-02-16 17:21 UTC
