### ISSUE TITLE
F680 from ISP - can't even read a signature

### ISSUE THREAD

**Issue by leshniak** [mkst/zte-config-utility#90] opened 2024-04-26 10:00 UTC
**Description of new feature**
This is a ZTE F680 from ISP, I cannot even read the signature due to an error in zcu module.

**Describe alternatives you've considered**
e.g. I have tried using --payload xxx but I get the following error < error >

**Additional context**
<img width="461" alt="Zrzut ekranu 2024-04-26 o 11 55 13" src="https://github.com/mkst/zte-config-utility/assets/752917/8e7edb22-e37f-4a0f-902c-3e9bda3c53b9">

```
# python3 examples/signature.py f680.bin
Traceback (most recent call last):
  File "/Users/leshniak/zte-config-utility/examples/signature.py", line 22, in <module>
    main()
  File "/Users/leshniak/zte-config-utility/examples/signature.py", line 16, in main
    zcu.zte.read_header(args.infile)
  File "/Users/leshniak/zte-config-utility/lib/python3.12/site-packages/zcu-0.4.0-py3.12.egg/zcu/zte.py", line 17, in read_header
AssertionError
```
```
Starting Nmap 7.94 ( https://nmap.org ) at 2024-04-26 12:04 CEST
Nmap scan report for 192.168.5.1
Host is up (0.0032s latency).
Not shown: 996 closed tcp ports (conn-refused)
PORT    STATE    SERVICE
23/tcp  filtered telnet
53/tcp  open     domain
80/tcp  open     http
443/tcp open     https

Nmap done: 1 IP address (1 host up) scanned in 1.87 seconds
```

**Attach config.bin for your device**
[f680.bin.zip](https://github.com/mkst/zte-config-utility/files/15128611/f680.bin.zip)

**Comment by mkst** [comment] 2024-08-24 18:17
Closing as dupe of https://github.com/mkst/zte-config-utility/issues/15.

**Closed by mkst** 2024-08-24 18:17 UTC
