### ISSUE TITLE
[FEATURE] Add support ZTE H3600 V9

### ISSUE THREAD

**Issue by Harun348** [mkst/zte-config-utility#94] opened 2024-06-15 01:05 UTC
I would like the ***ZTE H3600 V9*** router to be supported.

![zteh3600v9](https://github.com/mkst/zte-config-utility/assets/82382695/10c751f6-80ac-4da5-a2b9-402d7cc3c873)

**Comment by fagmixy** [comment] 2024-06-24 11:42
@Harun348  hello you have acces admin to your zte h3600 ?

**Comment by Harun348** [comment] 2024-06-24 11:48
@fagmixy hi.yes I have access to admin account

**Comment by fagmixy** [comment] 2024-06-26 22:11
``

> @fagmixy hi.yes I have access to admin account

You have digi h3600 can you help me to have password fro admin please

**Comment by sl1pkn07** [comment] 2024-07-30 14:19
Hi

same here please

greetings

**Comment by mkst** [comment] 2024-08-24 18:48
Closing as dupe of https://github.com/mkst/zte-config-utility/issues/76

**Closed by mkst** 2024-08-24 18:48 UTC

**Comment by imadknn** [comment] 2025-08-30 18:49
Can i have a admin password

**Comment by oussachy** [comment] 2025-12-12 16:09
[p1ezer](https://github.com/p1ezer) Can I have a admin password?

**Comment by registrospikakaka-sys** [comment] 2025-12-25 20:34
Can I ´ve a admin pass?? thanks!!

**Comment by driversat** [comment] 2026-04-24 21:15
> Can I ´ve a admin pass?? thanks!!

you have to open the box and connect TTL usb serial cable to pc.
i used this tutorial to get admin password:
https://orca.pet/zteh3600p/
