### ISSUE TITLE
AssertionError

### ISSUE THREAD

**Issue by FAlbanni** [mkst/zte-config-utility#42] opened 2022-05-09 09:59 UTC
This software used to work for me but not anymore, it seems they changed the encryption algorithm and now it can't even read the bin, now absolutely nothing works not even info.py or signature.py, all throws AssertionError on "zcu.zte.read_header(infile)"

Before when it worked the config.bin header was:

`00000000  04 03 02 01 00 00 00 00  00 00 00 04 46 36 37 30  |............F670|`

now is:

```
00000000  99 99 99 99 44 44 44 44  55 55 55 55 aa aa aa aa  |....DDDDUUUU....|
00000010  00 00 00 00 00 00 00 00  04 00 00 00 00 00 00 00  |................|
00000020  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
00000030  00 00 00 00 00 00 00 00  00 00 00 00 40 00 00 00  |............@...|
00000040  02 00 00 00 80 00 00 00  e8 69 00 00 00 00 00 00  |.........i......|
00000050  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
*
00000080  04 03 02 01 00 00 00 00  00 00 00 04 46 36 38 30  |............F680|
00000090  01 02 03 04 00 00 00 06  00 00 00 00 00 00 00 00  |................|
000000a0  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
*
```

**Comment by mkst** [comment] 2023-02-16 17:18
closing as dupe of https://github.com/mkst/zte-config-utility/issues/57

**Closed as completed by mkst** 2023-02-16 17:18 UTC
