### ISSUE TITLE
is it possible to root H168A v2.0 firmware locked by ISP Turk Telekom?

### ISSUE THREAD

**Issue by hypixelgamer** [mkst/zte-config-utility#79] opened 2023-08-17 19:10 UTC
Is the support for that going on?
Ill add the further details for my modem router if needed.

**Comment by pcislocked** [comment] 2023-09-01 14:34
Duplicate of #25.

**Comment by supertelekom** [comment] 2023-10-27 08:49
HELLO
Did you find a solution to this problem :(

**Closed** 2024-08-24 18:15 UTC
